apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-temp
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: failwin@ukr.net
    privateKeySecretRef:
      name: letsencrypt-temp
    solvers:
      - http01:
          ingress:
            class: nginx
