version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - nest-mono-nx:base
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: nest-mono-nx-api:base
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "development"
    networks:
      - corp
    restart: on-failure
